In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import glob
import json
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context('notebook')

In [19]:
def load_df_quick(df_loc):
    return pd.read_csv(df_loc, usecols=['classification_id', 'user_name'])

In [5]:
# first two moved to SSD for quick loading
pre_loc = '/home/walml/repos/gz-panoptes-reduction/temp/raw/decals-dr5-classifications.csv'
enhanced_loc = '/home/walml/repos/gz-panoptes-reduction/temp/raw/enhanced-classifications.csv'
classic_loc = '/media/walml/beta1/misc_downloads/classic-classifications.csv'

assert all([os.path.isfile(x) for x in [pre_loc, enhanced_loc, classic_loc]])
pre = load_df_quick(pre_loc)
classic = load_df_quick(classic_loc)
enhanced = load_df_quick(enhanced_loc)

In [7]:
# load classifications
dr1_c_loc = '/media/walml/beta1/galaxy_zoo/decals/gzreduction_ouroborous/working_dir/raw/classifications/2017-10-15_galaxy_zoo_decals_classifications.csv'
dr2_c_loc = '/media/walml/beta1/galaxy_zoo/decals/gzreduction_ouroborous/working_dir/raw/classifications/2017-10-15_galaxy_zoo_decals_dr2_classifications.csv'

In [13]:
dr1_c = pd.read_csv(dr1_c_loc, usecols=['id', 'user'])
dr2_c = pd.read_csv(dr2_c_loc, usecols=['id', 'user'])

In [23]:
# pd.read_csv(dr1_c_loc, nrows=10)

In [21]:
dr1_c

,id,subject_id,user,created_at,lang,user_agent,decals-0,decals-1,decals-2,decals-3,decals-4,decals-5,decals-6,decals-7,decals-8,decals-9,decals-10,decals-11
0,55e8b5061766270dbc005058,55a7d7a37a726119cd0006a0,KWillett,2015-09-03 21:00:54 UTC,en,unknown,a-1,a-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,55e8b5151766270fb100516a,55a7d7a27a726119cd000582,KWillett,2015-09-03 21:01:09 UTC,en,unknown,a-1,a-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,55e8b69117662710f8004e04,55a7d7a37a726119cd0007a1,KWillett,2015-09-03 21:07:29 UTC,en,unknown,a-1,a-1,a-0,a-0,a-2,a-1,a-2,NaN,NaN,a-1,a-0,a-0
3,55e8b6b417662710f8004e0d,55a7d7a37a726119cd0005e3,KWillett,2015-09-03 21:08:05 UTC,en,unknown,a-1,a-1,a-0,a-0,a-1,a-2,a-1,NaN,NaN,a-3,a-0,a-0
4,55e8b86e176627129b005008,55a7d7a27a726119cd00036c,KWillett,2015-09-03 21:15:26 UTC,en,unknown,a-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a-0,a-3,a-0,a-1
5,55e8b8731766273ff3004851,55a7d7a27a726119cd00041a,KWillett,2015-09-03 21:15:31 UTC,en,unknown,a-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a-1,a-3,a-0,a-1
6,55e8b8881766270dbc005142,55a7d7a37a726119cd0006a1,KWillett,2015-09-03 21:15:52 UTC,en,unknown,a-1,a-1,a-1,a-0,a-1,a-1,a-3,NaN,NaN,a-3,a-0,a-1
7,55e8b8a8176627132b0050f7,55a7d7a27a726119cd0002c8,KWillett,2015-09-03 21:16:24 UTC,en,unknown,a-1,a-1,a-1,a-0,a-1,a-1,a-2,NaN,NaN,a-3,a-0,a-1
8,55e8b8ac17662710f8004e85,55a7d7a27a726119cd0001a6,KWillett,2015-09-03 21:16:28 UTC,en,unknown,a-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a-1,a-3,a-0,a-1
9,55e8b8ba17662710f8004e8b,55a7d7a27a726119cd000148,KWillett,2015-09-03 21:16:42 UTC,en,unknown,a-1,a-1,a-1,a-1,a-2,NaN,NaN,NaN,NaN,a-3,a-0,a-1

In [16]:
pre['user_id'].dropna().unique()

array([2.904750e+05, 1.080000e+02, 1.530000e+03, ..., 1.903866e+06,
       1.903300e+06, 1.903864e+06])

In [24]:
# pd.read_csv(pre_loc, nrows=10)